# devops
technical:
  - '.github/**'

# yooso.js core and infrastructure
backend:
  - 'yooso-api/**'
  - 'yooso-core/**'
  - 'yooso-macro/**'
  - 'yooso-storage/**'

# yooso-studio client application
yooso-studio:
  - 'yooso-studio/**'

# libraries
yooso-cs:
  - 'yooso-cs/**'
yooso-go:
  - 'yooso-go/**'
yooso-js:
  - 'yooso-js/**'
yooso-py:
  - 'yooso-py/**'
yooso-rs:
  - 'yooso-rs/**'

# complex files that require special attention from code owner
wizard:
  - '.github/workflows/**'
  - 'yooso-macro/**'
  